### ISSUE TITLE
Stripe API issue

### ISSUE THREAD

**Issue by p1nngu** [J4c5/stripe-checker#3]
[ERROR] Request failed with error: Post "https://api.stripe.com/v1/payment_intents": dial tcp 34.204.109.15:443: i/o timeout

 It worked at the begining but now im having problems with the API , why?

**Comment by J4c5** [comment]
@p1nngu 
I need more details to fix it, call me on telegram @ jack2buffer this project is a beta for a checker project, it's been a while since I've updated it due to personal problems, but I intend to come back
